image: openjdk:8-jdk

before_script:
  - apt-get update -yqq
  - apt-get install apt-transport-https -yqq
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  - apt-get update -yqq
  - apt-get install sbt -yqq
  - apt-get install yarn -yqq
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get install -y nodejs

test:
  script:
    # Execute tests
    - sbt "project coreJVM" test
