image: java:8

before_script:
  # Enable the usage of sources over https
  - apt-get update -y
  - apt-get install apt-transport-https -y
  # Add keyserver for SBT
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  # Install SBT
  - apt-get update -y
  - apt-get install sbt -y
  # Log the sbt version
  - sbt sbt-version

test:
  script:
    # Execute tests
    - sbt clean test
